### ISSUE TITLE
speakersafetyd and rust 1.80

### ISSUE THREAD

**Issue by mrkcee** [AsahiLinux/speakersafetyd#15]
speakersafetyd is not compiling using rust 1.80 because `time`, one of its dependencies, is failing on rust 1.80. This has been raised upstream: https://github.com/rust-lang/rust/issues/127343. Based on the discussion in that link, it looks like they have opted to just let the packages that use `time` update to the newer version (>=0.3.35).

I tried building speakersafetyd locally with updated packages (via `cargo update`) and it was successful.

**Comment by mkurz** [comment]
Can confirm. I added `cargo update` in my PKGBUILD locally to compile the package with rust 1.80:
- https://github.com/AsahiLinux/PKGBUILDs/pull/40#issuecomment-2258585205

**Comment by joske** [comment]
@chadmed I see you bumped the lock file, so if you make a new tag, we don't have to adapt the PKGBUILD.

**Comment by chadmed** [comment]
New tag pushed. Thanks for bringing this up!

**Comment by dkwo** [comment]
@chadmed You may also want to update the version of speakersafetyd itself from 0.1.9 to 1.0.0 in the lockfile Cargo.lock, otherwise the package won't build with `--locked` or similar.
