### ISSUE TITLE
J316 panic

### ISSUE THREAD

**Issue by mavonarx** [AsahiLinux/speakersafetyd#8]
➜  ~ sudo speakersafetyd
INFO [speakersafetyd] Starting up
INFO [speakersafetyd] Config base: "/usr/local/share/speakersafetyd"
INFO [speakersafetyd] Machine: apple,j316
INFO [speakersafetyd] Config file: "/usr/local/share/speakersafetyd/apple/j316.conf"
INFO [speakersafetyd] Device: hw:AppleJ316
INFO [speakersafetyd::uclamp] Set task uclamp to 0:64
INFO [speakersafetyd] Found 6 speakers
INFO [speakersafetyd] Opening control device
INFO [speakersafetyd] Startup mode: Cold boot
INFO [speakersafetyd::types] Speaker [Left Woofer 1]:
thread 'main' panicked at src/helpers.rs:172:13:
Could not lock elem Left Woofer 1 VSENSE Switch. alsa-lib error: Error("snd_ctl_elem_lock", EBUSY)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
WARN [speakersafetyd] Panic!

➜  ~ sudo speakersafetyd
INFO [speakersafetyd] Starting up
INFO [speakersafetyd] Config base: "/usr/local/share/speakersafetyd"
INFO [speakersafetyd] Machine: apple,j316
INFO [speakersafetyd] Config file: "/usr/local/share/speakersafetyd/apple/j316.conf"
INFO [speakersafetyd] Device: hw:AppleJ316
INFO [speakersafetyd::uclamp] Set task uclamp to 0:64
INFO [speakersafetyd] Found 6 speakers
INFO [speakersafetyd] Opening control device
INFO [speakersafetyd] Startup mode: Warm boot
INFO [speakersafetyd::types] Speaker [Left Woofer 1]:
thread 'main' panicked at src/helpers.rs:172:13:
Could not lock elem Left Woofer 1 VSENSE Switch. alsa-lib error: Error("snd_ctl_elem_lock", EBUSY)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
WARN [speakersafetyd] Panic!

Speakers didn't activate after upgrading to the recent patch. So I tried to to activate speakersafetyd by my own. But it seems to crash while locking the Left Woofer. Can you help me with that?

**Comment by jannau** [comment]
Looks like this a self-managed system. Due to a [bug in lsp-plugins](https://github.com/lsp-plugins/lsp-dsp-lib/pull/20) speaker enablement needs out of tree patches to ensure speakers are only enabled on systems with fix lsp-plugins.

See the `speakers/enablement-READ-COMMIT-MESSAGE` branch in the linux repo.

**Comment by mavonarx** [comment]
Hmm i installed it quite a while ago woth fedora installer. 
I just do dnf upgrade --refresh regularly to update the system but nothing else.

**Comment by mavonarx** [comment]
Reinstalled fedora with installer
