### ISSUE TITLE
Gain reduction exceeded threshold panic

### ISSUE THREAD

**Issue by iaguis** [AsahiLinux/speakersafetyd#9]
I got a "Gain reduction exceeded threshold panic" when playing ["Tame Impala - Let it Happen" on YouTube Music](https://music.youtube.com/watch?v=NMRhx71bGo4&si=9DqXOsqcgnuIOq5v) at a high volume, I think it was 95%.

[blackbox](https://www.dropbox.com/scl/fi/b4t03ioife40xdk7h6xz4/speakersafetyd-blackbox-tame-impala-let-it-happen.tar.gz?rlkey=iudo9xzr2xcjpkigwiwhhtp6l&dl=0)
[asahi-diagnose-20231221-094817.txt](https://github.com/AsahiLinux/speakersafetyd/files/13739309/asahi-diagnose-20231221-094817.txt)

**Comment by chadmed** [comment]
I was never able to reproduce this. Is it still happening?

**Comment by iaguis** [comment]
I haven't seen it since, so feel free to close this. Thanks!

**Comment by chadmed** [comment]
Thanks!
